#! /bin/bash
cd "$(dirname "$0")"
basedir="$(pwd)"

for prog in packwriter; do
  dir="$(mktemp -d -t buildXXXXX)"
  javac -d "$dir" $(find "$basedir/src/java/$prog" -type f -name '*.java') ||
    { echo "$prog: javac failed."; rm -rf "$dir"; exit 1; }
  cd "$dir"
  jar cmf "$basedir/src/$prog-manifest.mf" "$basedir/lib/java/$prog.jar" $(find . -type f -name '*.class') ||
    { echo "$prog: jar failed."; rm -rf "$dir"; exit 1; }
done
  
cd "$basedir"
rm -rf $dir
